[package]
org = "matheusmulundu"
name = "graphql"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerinax/java.jdbc" = "1.11.0"


[[platform.java11.dependency]]
# module = "mysql"
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

[[platform.java11.dependency]]
artifactId = "h2"
version = "2.0.206"
groupId = "com.h2database"